Reddit example
Assets/Standard
Assets/Characters/ThirdPersonCharacter/Scripts/ThirdPersonUserControl.cs(21,13):
error CS0246: The type or namespace name `SpellManager' could not be
found. Are you missing a using directive or an assembly reference?